[package]
name = "denovorust_app"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"

[lib]
name = "testlib"  # Specify the name of your library crate
path = "src/peak.rs"  # Path to your library source file


